language: java

deploy:
  provider: heroku
  api_key:
    secure: OkNXY4gIe9a4hD/p5GkIgWmAnKnR9bD4D+Ug8cPtizDUMYI19KF1xvxsa6JXG8K6zxpBCETDVBIZGRk5Xj1mxrv1gyewMyG0L/yQTnwDHF2LuIXp8iVBlKtDyb297mJn3INcsWiZg4puNsWhOYIt+VVCjKKJhkq4aI1kaeRnlB3cV8sxSRrkmY7a6txGVNK05AnatM9jkeMkMvKxZZOkZ3s1lqg6bGmKCZwbeqR/0u8Zin/Wou4nw0WABdEXbX4pwdmPRd1wCbThs4WQixGq7J7uTmevwa7iF/nlY+LYHQGFVRYLBZ+Y0eFdLRTgNO1uPWfLZ50uujFxcIVXyqCdtLD85iFw5qVJfVXBKP2AEe/Al26m6Uux0zJys+KkpegnrH1/hQ4l/cH4xnh2vqrxaIOpdseihhTrphX5L+3q153SUMNChCvzfPhXRgMZ9ZZWWgNddV+KTA/FGqX6qwZT20FO+T5AASgXO7tXCtsXq7CnJMYEoHlumxjFRqMmrSW3iwT9tNGAPrUU6O4TnhwDVK4KShTOqPufvHzGX+mevCdfEn8QJ74PBQHPc6fAe/xh9EBmWWEY8P6Td4KYlGGClu7k+IlFZbK6v8lnEOJtEK6a1+usrh6gdUDiEuSb64DNmQFK04HLS3qIwVvz2K3E2xh3TS6IiCZI0GRC02MJIZ4=
  app: geneeriset-uutiset
  on: true
